# Generated by Django 5.1 on 2024-09-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_addresort_delete_addroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresort',
            old_name='bed',
            new_name='bedtype',
        ),
        migrations.RenameField(
            model_name='addresort',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='addresort',
            old_name='roomno',
            new_name='rno',
        ),
        migrations.RenameField(
            model_name='addresort',
            old_name='type',
            new_name='roomtype',
        ),
    ]
